# Example of a private Web Server that can be only accessed using an smart phone.
# Here connect to Wifi ID "Thetis" then open browser using URL access.local/
# Demonstrates a pump control with low and high water sensors.
# Internal state is set with press on low water sensor and cleared with press of high water sensor

# Support is easy.
# With the ota option of the web_server set to true, the firmware can be compiled from this file
# and emailed to Thetis for updating.  The email attachment is saved in Files on the iPhone.
# Under OTA Update on the access.local screen, choose the saved file (access.bin) and touch Update.
# (The iPhone screen has to be rotated to see the UPDATE button on the far right.)

esphome:
  name: access
  friendly_name: Desalination
  on_boot:
    lambda: |-
        auto call0 = id(salt_water_level_cal_slide).make_call();
        call0.set_value(id(salt_water_level_cal));
        call0.perform();
        auto call1 = id(fresh_water_level_cal_slide).make_call();
        call1.set_value(id(fresh_water_level_cal));
        call1.perform();
        auto call2 = id(salt_water_level_low_slide).make_call();
        call2.set_value(id(salt_water_level_low));
        call2.perform();
        auto call3 = id(fresh_water_level_low_slide).make_call();
        call3.set_value(id(fresh_water_level_low));
        call3.perform();

esp8266:
  board: d1_mini
  restore_from_flash: True


# Enable logging
logger:
  level: debug

globals:
  - id: save_month
    type: int
    restore_value: True
  - id: save_day
    type: int
    restore_value: True
  - id: salt_water_level_cal  #Analog voltage time this value = 100 and full tank
    type: int
    restore_value: True
  - id: fresh_water_level_cal
    type: int
    restore_value: True
  - id: salt_water_level_low #Percentage of full tank
    type: int
    restore_value: True
  - id: fresh_water_level_low
    type: int
    restore_value: True

wifi:
  ap:
    ssid: "Thetis"
    password: "SmiLinCove216"

web_server:
  port: 80
  version: 3
  ota: true
  log: true
  local: true
  sorting_groups:
    - id: sorting_group_message
      name: "Message"
      sorting_weight: 1
    - id: sorting_group_pumps
      name: "Pumps"
      sorting_weight: 3
    - id: sorting_group_levels
      name: "Levels"
      sorting_weight: 2
    - id: sorting_group_other
      name: "Other"
      sorting_weight: 4
    - id: sorting_group_timeset
      name: "Time Set"
      sorting_weight: 5
    - id: sorting_group_config
      name: "Config"
      sorting_weight: 6
# Identify the version on startup
# and then use for state messages
text_sensor:
  - platform: template
    name: "Status"
    id: message_text
    web_server:
      sorting_group_id: sorting_group_message
# Show my firmware version
    lambda: |-
      return {"v1.0"};
  - platform: template
    name: "Time"
    id: time_text
    web_server:
      sorting_group_id: sorting_group_message
# Show current time
    lambda: |-
      return {to_string(id(save_month)) + "/" + to_string(id(save_day)) };

binary_sensor:
  - platform: gpio
    name: "Water Low"
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: set_state
    web_server:
      sorting_group_id: sorting_group_levels
    on_press:
      then:
        - binary_sensor.template.publish:
            id: internal_state
            state: ON
        - switch.turn_on: boost_pump
# Update message when state changes
        - text_sensor.template.publish:
            id: message_text
            state: "Water Low Detected"

  - platform: gpio
    name: "Water Full"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: clear_state
    web_server:
      sorting_group_id: sorting_group_levels
    on_press:
      then:
        - binary_sensor.template.publish:
            id: internal_state
            state: OFF
        - switch.turn_off: boost_pump
        - text_sensor.template.publish:
            id: message_text
            state: "Water Full Detected"

  - platform: template
    id: internal_state
    name: "Internal State"
    internal: true
    lambda: |-
      if (id(internal_state).state) {
        return true;
      } else {
        return false;
      }
    on_state:
      - then:
          - if:
              condition:
                binary_sensor.is_on: internal_state
              then:
                - switch.turn_on: hp_pump
              else:
                - switch.turn_off: hp_pump

light:
  - platform: status_led
    name: "Status LED"
    id: led_status
    web_server:
          sorting_group_id: sorting_group_other
    pin: 
      number: GPIO2
      inverted: True

switch:
  - platform: gpio
    name: "HP Pump"
    id: hp_pump
    web_server:
      sorting_group_id: sorting_group_pumps
    pin:
      number: GPIO12
      inverted: True
  - platform: gpio
    name: "Boost Pump"
    id: boost_pump
    web_server:
      sorting_group_id: sorting_group_pumps
    pin: GPIO1
  - platform: template
    name: "Saltwater Enable"
    id: sw_enable
    optimistic: True
    web_server:
      sorting_group_id: sorting_group_other
  - platform: template
    name: "Desal Enable"
    id: desal_enable
    optimistic: True
    web_server:
      sorting_group_id: sorting_group_other

number: 
  - platform: template 
    name: "Fill Set Point"
    id: my_slide
    web_server:
      sorting_group_id: sorting_group_other
    optimistic: true
    mode: slider
    min_value: 0
    max_value: 100
    step: 0.1
    initial_value: 30
  - platform: template 
    name: "_Month"
    id: month_slide
    web_server:
      sorting_group_id: sorting_group_timeset
    optimistic: true
    mode: slider
    min_value: 1
    max_value: 12
    step: 1
  - platform: template 
    name: "Day"
    id: day_slide
    web_server:
      sorting_group_id: sorting_group_timeset
    optimistic: true
    mode: slider
    min_value: 1
    max_value: 31
    step: 1
  - platform: template 
    name: "Hour"
    id: hour_slide
    web_server:
      sorting_group_id: sorting_group_timeset
    optimistic: true
    mode: slider
    min_value: 0
    max_value: 23
    step: 1
  - platform: template 
    name: "Minute"
    id: minute_slide
    web_server:
      sorting_group_id: sorting_group_timeset
    optimistic: true
    mode: slider
    min_value: 0
    max_value: 59
    step: 1
  - platform: template 
    name: "SW Level Cal"
    id: salt_water_level_cal_slide
    web_server:
      sorting_group_id: sorting_group_config
    optimistic: true
    mode: slider
    min_value: 0
    max_value: 1000
    step: 1
  - platform: template 
    name: "FW Level Cal"
    id: fresh_water_level_cal_slide
    web_server:
      sorting_group_id: sorting_group_config
    optimistic: true
    mode: slider
    min_value: 0
    max_value: 1000
    step: 1
  - platform: template 
    name: "SW Low Cal"
    id: salt_water_level_low_slide
    web_server:
      sorting_group_id: sorting_group_config
    optimistic: true
    mode: slider
    min_value: 1
    max_value: 50
    step: 1
  - platform: template 
    name: "FW Low Cal"
    id: fresh_water_level_low_slide
    web_server:
      sorting_group_id: sorting_group_config
    optimistic: true
    mode: slider
    min_value: 1
    max_value: 50
    step: 1

button:
  - platform: template
    name: "Set Time"
    id: set_time_button
    web_server:
      sorting_group_id: sorting_group_timeset
    on_press:
      lambda: |-
        id(save_month) = id(month_slide).state;
        id(save_day) = id(day_slide).state;
        id(time_text).publish_state(to_string(id(save_month)) + "/" + to_string(id(save_day)));
  - platform: template
    name: "~Save Configuration"
    id: safe_config
    web_server:
      sorting_group_id: sorting_group_config
    on_press:
      lambda: |-
        id(salt_water_level_cal) = id(salt_water_level_cal_slide).state;
        id(fresh_water_level_cal) = id(fresh_water_level_cal_slide).state;
        id(salt_water_level_low) = id(salt_water_level_low_slide).state;
        id(fresh_water_level_low) = id(fresh_water_level_low_slide).state;

# Required for I2C connected sensors
i2c:
  scan: true

# Included as example of analog reading
# Another sealed temperature sensor would be used instead of the bme_280
# Note that turning on/off a light is different than a switch
# Here both the boost pump switch and the LED status light
#  are turned ON if the temperature exceeds the fill set point.  Just a crazy example to test coding.
sensor:
  - platform: bme280_i2c
    temperature:
      name: "HP Pump Temperature"
      oversampling: 16x
      id: pump_temp
      web_server:
        sorting_group_id: sorting_group_other
      on_value:
        then:
          - lambda: |-
              if (id(pump_temp).state > id(my_slide).state) {
                id(boost_pump).turn_on();
                auto call = id(led_status).turn_on();
                call.perform();
              } else {
                id(boost_pump).turn_off();
                auto call = id(led_status).turn_off();
                call.perform();
              }
    address: 0x77
    update_interval: 10s

    
      
        