logger:
  level: none
 
esphome:
  name: cellar
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.81
    gateway: 192.168.1.254
    subnet: 255.255.255.0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Winecellar Temperature"
      filters:
      - delta: 0.2
    humidity:
      name: "Winecellar Humidity"
      filters:
      - delta: 1
    update_interval: 10s
    model: DHT22