logger:
  level: DEBUG

substitutions:
  node_name: hepa
  
esphome:
  name: ${node_name}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password


# Ground D2 when switch is ON in HA
switch:
  - platform: gpio
    name: hepa
    inverted: true
    pin: 
      number: D5
      mode: OUTPUT_OPEN_DRAIN
  


  
