logger:
  level: none

esphome:
  name: ms3
  #80 MHz is the lowest possible frequency
  platformio_options:
    board_build.f_cpu: 80000000L
  # Used to verify that the CPU frequency was set to 80 MHz
  #includes:
  #  - cpufreq.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.108
    gateway: 192.168.1.254
    subnet: 255.255.255.0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

i2c:
  sda: 21
  scl: 22
  scan: true

bme680_bsec:
  address: 0x76
  temperature_offset: 2.1
  sample_rate: ulp

sensor:
  - platform: bme680_bsec
    temperature:
      name: "MS3 Temperature"
      filters:
        - median
      sample_rate: lp
    pressure:
      name: "MS3 Pressure"
      filters:
        - median
      sample_rate: ulp
    humidity:
      name: "MS3 Humidity"
      filters:
        - median
      sample_rate: ulp
    gas_resistance:
      name: "MS3 Gas Resistance"
      filters:
        - median
    iaq:
      name: "MS3 IAQ"
      id: iaq
    co2_equivalent:
      name: "MS3 CO2 Equivalent"
    breath_voc_equivalent:
      name: "MS3 Breath VOC Equivalent"
  
  - platform: wifi_signal
    name: "MS3 RSSI"
    update_interval: 60s

  #- platform: custom
  #  lambda: |-
  #    auto cpufreq = new MyCPU();
  #    App.register_component(cpufreq);
  #    return {cpufreq->cpu_sensor};
  #  sensors:
  #  - name: "CPU Frequency"
  #    unit_of_measurement: MHz
  #    accuracy_decimals: 0

  # Used to see if CPU frequency option has any affect
  #- platform: internal_temperature
  #  name: "MS3 CPU Temperature"

#RGB LED, Brightness determined by PWM 
# Use max_power to balance color
output:
  - platform: ledc
    pin: GPIO14
    id: red_led
    frequency: 4882
    inverted: true
    max_power: 80%

  - platform: ledc
    pin: GPIO5
    id: green_led
    frequency: 4882
    inverted: true
    max_power: 80%

  - platform: ledc
    pin: GPIO18
    id: blue_led
    frequency: 4882
    inverted: true
    max_power: 80%

light:
  - platform: rgb
    name: "MS3 Light"
    red: red_led
    green: green_led
    blue: blue_led

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "MS3 IAQ Accuracy"

  - platform: template
    name: "MS3 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }