logger:
  level: DEBUG

substitutions:
  node_name: plants
  
esphome:
  name: ${node_name}
  platform: ESP8266
  board: nodemcuv2
  platformio_options:
    lib_deps: diaoul/DHTNew@1.0.0

wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.104
    gateway: 192.168.1.254
    subnet: 255.255.255.0

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password
  
  
switch:
  - platform: gpio
    pin: 14
    name: "Plant Light"
  - platform: gpio
    pin: 12
    name: "Plant Heater"
  - platform: gpio
    pin: 13
    name: "Plant Dehumidifier"

dallas:
- pin: GPIO10
  update_interval: 10s
  
external_components:
### This long form works. refresh option is only needed for changes less than 24 hours old
  - source:
      type: git
      url: https://github.com:/gb53smith/esphome
      ref: main
    components: [dht]
    refresh: 0s
### Use this local copy to debug, the commit to github
  #- source: my_components

sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Plants Temperature"
      filters:
      - delta: 0.2
    humidity:
      name: "Plants Humidity"
      filters:
      - delta: 1
    update_interval: 10s
    model: DHT22
  - platform: dallas
    address: 0x1F3C01B556A19A28
    name: "Plants Soil Temperature"
    filters:
    - delta: 0.2
    

