# Enable logging
logger:
  level: DEBUG

esphome:
  name: rssi
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.86
    gateway: 192.168.1.254
    subnet: 255.255.255.0

ota:
  - platform: esphome
    password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
   key: !secret api_encryption_key
     
binary_sensor:
  - platform: gpio
    name: "Rssi button"
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: True

light:
  - platform: binary
    name: "Rssi LED"
    id: light1
    output: output1

output:
  - platform: gpio
    pin: D6
    inverted: True
    id: output1

status_led:
  pin:
    number: GPIO2
    inverted: yes

i2c:
  scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 60s

